# Generated by Django 5.2.7 on 2025-10-14 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financialapp', '0002_asset_expense_income_liability'),
        ('financialapp', '0003_initial_data'),
    ]

    operations = [
    ]
