# Generated by Django 5.2.7 on 2025-10-15 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financialapp', '0005_financialreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
