# Generated by Django 5.2.7 on 2025-10-15 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financialapp', '0006_alter_asset_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='liabilitytype',
            name='pill_color',
            field=models.CharField(default='primary', max_length=50),
        ),
    ]
