# Generated by Django 5.2.7 on 2025-10-15 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financialapp', '0007_liabilitytype_pill_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='current_value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='asset',
            name='monthly_income',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='asset',
            name='purchase_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='net_cash_flow',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='total_expenses',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='cashflow',
            name='total_income',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='income',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='liability',
            name='current_balance',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='liability',
            name='interest_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='liability',
            name='monthly_payment',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='liability',
            name='original_amount',
            field=models.FloatField(),
        ),
    ]
