# Generated by Django 5.2.7 on 2025-10-15 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financialapp', '0009_moneyrelatedsms'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='moneyrelatedsms',
            table='money_related_sms',
        ),
    ]
