# Generated by Django 5.2.7 on 2025-10-15 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financialapp', '0010_alter_moneyrelatedsms_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneyrelatedsms',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
