# Generated by Django 5.2.7 on 2025-10-15 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financialapp', '0011_moneyrelatedsms_is_processed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moneyrelatedsms',
            old_name='description',
            new_name='message',
        ),
    ]
