# Generated by Django 5.2.7 on 2025-10-18 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financialapp', '0013_keywordexpensetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneyrelatedsms',
            name='expense_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='financialapp.expensetype'),
        ),
        migrations.AddField(
            model_name='moneyrelatedsms',
            name='income_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='financialapp.incometype'),
        ),
    ]
